package com.example.tienda.util;

public enum Permisos {

    // TIENDA
    READ_ALL_TIENDA, // 

    // PRODUCTO
    READ_ALL_PRODUCTS_ADMIN,
    READ_ALL_ACTIVES_ADMIN,
    READ_ALL_INACTIVES_ADMIN,
    SEARCH_PRODUCT_ID_ADMIN,
    SEARCH_PRODUCT_NAME_ADMIN, 
    SEARCH_PRODUCT_MARCA_USER, //
    SEARCH_PRODUCT_CATEGORY_USER, //
    SEARCH_PRODUCT_BARRA_USER, //
    SAVE_ONE_PRODUCT,
    EDIT_ONE_PRODUCT,
    DELETE_PRODUCT,
    CHANGE_ACTIVIDAD_PRODUCT,
    REPORT_PDF_PRODUCT,
    REPORT_EXCEL_PRODUCT,

    // CATEGORIA
    READ_ALL_CATEGORY,
    READ_ALL_ACTIVE_CATEGORY,
    READ_ALL_INACTIVE_CATEGORY,
    SEARCH_CATEGORY_ID,
    SAVE_CATEGORY,
    EDIT_CATEGORY,
    CHANGE_ACTIVIDAD_CATEGORY,
    DELETE_CATEGORY,

    // ESTADO PRODUCTO
    READ_ALL_ESTADO_PRODUCTO,
    READ__ALL_ACTIVE_ESTADO_PRODUCTO,
    READ_ALL_INACTIVE_ESTADO_PRODUCTO,
    SEARCH_ESTADO_PRODUCTO_ID,
    SAVE_ESTADO_PRODUCTO,
    EDIT_ESTADO_PRODUCTO,
    CHANGE_ACTIVIDAD_ESTADO_PRODUCTO,
    DELETE_ESTADO_PRODUCTO,

    // MARCA
    READ_ALL_MARCA,
    READ_ALL_ACTIVE_MARCA,
    READ_ALL_INACTIVE_MARCA,
    SEARCH_MARCA_ID,
    SAVE_MARCA,
    EDIT_MARCA,
    CHANGE_ACTIVIDAD_MARCA,
    DELETE_MARCA,

    // PROVEEDOR
    READ_ALL_PROVEEDOR,
    READ_ALL_ACTIVE_PROVEEDOR,
    READ_ALL_INACTIVE_PROVEEDOR,
    SEARCH_ID_PROVEEDOR,
    SEARCH_NAME_PROVEEDOR,
    SAVE_PROVEEDOR,
    EDIT_PROVEEDOR,
    CHANGE_ACTIVIDAD_PROVEEDOR,
    DELETE_PROVEEDOR,
    REPORT_PDF_PROVEEDOR,
    REPORT_EXCEL_PROVEEDOR

}
